### ISSUE TITLE
Allow passing Entity types to delete_multi in addition to Key types.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-datastore#122]
Branched off from https://github.com/googleapis/python-datastore/issues/118

`delete` and `delete_multi` require a List of `Key`, but could possibly take `Entity`

Currently:
```
query = client.query(kind='Task')
query.keys_only()
entities = query.fetch()
keys = [i.key for i in entities]
client.delete_multi(keys)
```

Proposed:
```
query = client.query(kind='Task')
query.keys_only()
entities = query.fetch()
client.delete_multi(entities)
```

This would also better support conversion from NDB as fetch can return entities or keys based on the keys_only flag.

**Comment by wescpy** [comment]
The proposed solution is more "Pythonic" IMO because it pushes down "getter grunt work" as a level of abstraction shielding the developer from said effort, reducing the lines of code necessary to delete entities. This update should automatically apply to `delete()` as well, esp. since it wraps `delete_multi()` per [the docs](https://googleapis.dev/python/datastore/latest/client.html?highlight=delete_multi#google.cloud.datastore.client.Client.delete).
